      language: node_js
      node_js:
       - "0.10"
      env:
       - TEST_COMMAND="meteor"
      before_install:
       - "curl -L http://git.io/ejPSng | /bin/sh"
      branches:
        only:
          - master
